version: '3.8'

services:
  # Frontend (React + Vite)
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    command: npm run dev

  # Backend (Python FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Database (SQLite file wird gemountet)
  # Für später: PostgreSQL wenn nötig
  # database:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: trading_app
  #     POSTGRES_USER: trading_user
  #     POSTGRES_PASSWORD: trading_pass
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
